export const zhNavigation: Record<string, string> = {
  "Dashboard": "仪表盘",
  "Analytics": "数据分析",
  "Inbox": "收件箱",
  "WhatsApp Inbox": "WhatsApp 收件箱",
  "WhatsApp QR Inbox": "WhatsApp 二维码收件箱",
  "Instagram Inbox": "Instagram 收件箱",
  "Facebook Inbox": "Facebook 收件箱",
  "Telegram Bot Inbox": "Telegram 机器人收件箱",
  "Personal Telegram Inbox": "Telegram 个人收件箱",
  "Email Inbox": "邮件收件箱",
  "Campaigns": "BMS群发",
  "Message Templates": "消息模板",
  "Broadcast": "群发消息",
  "Smart Broadcast": "智能群发",
  "Drip Campaigns": "分阶段营销",
  "Save Money": "普通群发",
  "Preset Templates": "预设模板",
  "Preset Campaigns": "预设营销活动",
  "Web WhatsApp Campaigns": "网页版 WhatsApp 群发",
  "Contacts": "联系人",
  "Contact Directory": "联系人列表",
  "Segments": "联系人分组",
  "Labels": "标签",
  "Stage/Pipeline": "客户阶段与销售漏斗",
  "Data Fields": "数据字段",
  "Import Logs": "导入日志",
  "Lead CRM": "潜在客户管理",
  "Lead Dashboard": "潜在客户概览",
  "Lead Report": "潜在客户报告",
  "CRM 360": "CRM 360",
  "Pipeline Board": "销售漏斗看板",
  "Automation": "自动化",
  "Automation Flows": "自动化流程",
  "Bulk AI Calls": "AI 批量通话",
  "Bot Flow Builder": "机器人流程设计器",
  "AI Follow-ups": "AI 自动跟进",
  "Flow Builder": "流程设计器",
  "Quick Replies": "快捷回复",
  "Keyword Triggers": "关键词触发",
  "Appointments": "预约",
  "Tickets": "工单",
  "Leads & Commerce": "获客与商城",
  "All Leads": "全部潜在客户",
  "Lead Gen Forms": "获客表单",
  "Facebook Leads": "Facebook 潜在客户",
  "Product Catalogs": "产品目录",
  "Order Management": "订单管理",
  "Short Links": "短链接",
  "Channels": "渠道",
  "Channel Config": "渠道配置",
  "WhatsApp Settings": "WhatsApp 设置",
  "Settings": "设置",
  "Organization Teams": "团队管理",
  "Agents": "客服管理",
  "Integrations": "集成配置",
  "Chat Appearance": "聊天外观",
  "AI Settings": "AI 设置",
  "AI Calling Settings": "AI 通话设置",
  "Knowledge Base": "知识库",
  "Audit Log": "审计日志",
  "Business Settings": "工作区设置",
  "Subscription & Plans": "订阅与套餐",
  "Subscription Plans": "订阅套餐",
  "Billing & Wallet": "账单与钱包",
  "Transactions": "交易记录",
  "Invoices": "发票",
  "Media Library": "媒体库",
  "CTWA Ads": "CTWA 广告",
  "Instagram Auto DM": "Instagram 自动私信",
  "API & Developers": "API 与开发者",
  "Support": "帮助与支持",
  "User Guide": "用户指南",
  "Vendors": "商户管理",
  "Feature Controls": "功能开关",
  "Data Cleanup": "数据清理",
  "Accounting": "财务管理",
  "Payments": "支付记录",
  "Wallet Ledger": "钱包流水",
  "Subscriptions": "订阅管理",
  "Billing & Invoices": "账单与发票",
  "Taxes": "税费管理",
  "Plan Reminders": "套餐到期提醒",
  "Plans": "套餐管理",
  "Inquiries": "咨询消息",
  "Coupons": "优惠券",
  "Announcements": "公告",
  "System Health": "系统状态",
  "One Click Signup": "一键注册",
  "My Profile": "个人资料",
  "Site Settings": "站点设置",
  "Gateway Setup": "支付网关配置",
  "System Settings": "系统设置",
  "AI Intelligence": "AI 服务配置",
  "Permissions": "权限管理",
  "Blog": "博客",
  "Staff & Members": "员工与成员",
  "Languages": "语言",
  "Currencies": "货币",
  "Client API Docs": "客户端 API 文档",
  "Panel Updates": "系统更新",
  "License & Updates": "许可证",
  "Support Tickets": "支持工单",
  "Affiliate Partners": "联盟伙伴",
  "Partners": "合作伙伴",
  "Referrals": "推荐",
  "Commissions": "佣金",
  "Withdraw Requests": "提款请求",
  "KYC": "KYC",
  "Reports": "报告",
  "Website Chat Inbox": "Website Chat Inbox",
  "Sequence Campaigns": "序列营销活动",
  "Custom Fields": "自定义字段",
  "Migration": "数据迁移",
  "Call Logs": "通话记录",
  "Automations": "自动化",
  "Teams & Agents": "团队和代理",
  "Chat Widget": "聊天小工具",
  "Lead Source & QR": "链接生成",
  "AI Assistant": "AI 助手",
  "Tracked Links": "链接追踪"
};
